### ISSUE TITLE
Installing Packages on VM

### ISSUE THREAD

**Issue by medim** [maxonthegit/netkit-core#26]
Hi,

Sorry if my question is too simple, I just want to add some common debian packages and perl modules (Net::BGP and its requirements). I followed all instructions and tries both ways of installing directly from the Internet (tap if) and mounting the file system on host. 
But none was successful, the disaster happens after 'apt-get update' and even for some simple packages like gcc and make it needs 100 dependencies to be installed and while installing them gets stuck and gives error, in fact I was not able even to install one package.
Your help is highly appreciated.

Cheers,
Medi

**Comment by maxonthegit** [comment]
Hi,

I have made a quick check and succeeded in installing gcc, make, and perl modules with the following sequence of commands:
1. (host-side) vstart pc1 --eth0=tap,10.0.0.1,10.0.0.2 -M 256
2. [copy your host resolv.conf to pc1]
3. apt-get update
4. apt-get install -y --force-yes debian-keyring debian-archive-keyring
   (not really required, just to silence some warnings about unauthenticated packages)
5. apt-get update
6. apt-get install -y locales
   (not really required, just to silence other warnings about unset locale - and it would be pulled in by dependencies anyway)
7. apt-get install -y make gcc perl gzip
   (this will take a while to complete - perl is also included in case you want to upgrade it)
8. cpan App:cpanminus
   (going with the defaults - note: for some mysterious reason, I had to do this twice)
9. cpanm Net::BGP
   
   There you go.

This is a pretty standard sequence for a Debian system, and I could not see any errors by following it. Note: I did not use the -W option of vstart because I did not want to change my filesystem permanently. Depending on your goal, you may want to do that instead.

Please report back your own experience.

Regards,
Massimo

**Comment by medim** [comment]
Thanks a million for your useful, accurate and early reply.

I totally worked for me and saved the whole my research :) now everything is quite fine. I had tried different kernels even manually complied ones and was not successful. thanks, I am going to give a 'BIG' acknowledgement to it in my dissertation.

Medi

**Comment by maxonthegit** [comment]
You're welcome :-)
