### ISSUE TITLE
Connecting to VM's Console using port:#

### ISSUE THREAD

**Issue by medim** [maxonthegit/netkit-core#28]
Hi,

In order to get the console access to a machine via port number (reverse telnet) I modified the netkit.conf like this:
VM_CON0=xterm
VM_CON1=port:3000
TERM_TYPE=xterm
or
VM_CON0=none
VM_CON1=port:3000
TERM_TYPE=none

(I have also swapped CON0 and CON1's values)

and also have tried command based as well:
vstart ... con0=null con1=port:3000 

but when telneting to the corresponding port (telnet localhost 3000) I got this error:
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

I was wondering if you'd mind letting me know if I am following the right thing, or what I can do if don't want to have my VMs' console opened when I start my scenario ? actually I have lots of quagga routers on a remote machine and I need to only work on a couple of them no all, while all others are running.

Many thanks,
Mehdi

**Comment by maxonthegit** [comment]
Using TCP ports to access virtual machine terminals requires a telnet server installed **_host_**-side.

This should solve your problem, but consider that this connection mechanism works only the first time you attempt to contact the virtual machine. If you close the connection, you will not be able to contact the virtual machine any longer.
Also, due to a bug, the mechanism only works for CON1, not CON0, but I see that for you it does not make any real difference.

If you have the possibility, I suggest using an ssh server and a tap interface to make the virtual machines of interest reachable from the host.

**Comment by medim** [comment]
Thank you so much, actually I have a scenario of multiple quagga/netkit vms, dynamips routers and kvm vms , it is really confusing to have all those netkit consoles open :( 

And thanks for the suggestion of using ssh server and tapif. however, I was wondering if there is a way not to use automatically binding and tapif generation of netkit (--eth0=tap,192.168.200.5,192.168.200.10) because I want to bind vm's to some certain existing tap interfaces manually. The method I am using now is putting netkit generated interface and my own tap in a same vir-bridge. Also I do not need the NAT function and iptable rule modification. Is there a way to do that ?

Cheers,
Mehdi

**Comment by maxonthegit** [comment]
At present the Netkit interface does not allow fine customization of the tap interface setup, but you have (at least) three other options, a bit more technically involved but viable:
- to configure just one vm with a tap interface and make it act as a router to other vms;
- to alter the tap interface setup after it has been made by Netkit;
- to modify the script `$NETKIT_HOME/bin/manage_tuntap` according to your needs.
